# Generated by Django 5.0.7 on 2025-11-16 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_project_systemstatus_testimonial_lead"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hero_title",
                    models.CharField(
                        default="Premium Living Spaces in Karimnagar",
                        help_text="Main hero section title",
                        max_length=255,
                    ),
                ),
                (
                    "hero_subtitle",
                    models.TextField(
                        default="Discover your dream home with HSR Green Homes - where quality meets comfort",
                        help_text="Hero section subtitle/description",
                    ),
                ),
                (
                    "hero_background_image",
                    models.URLField(
                        blank=True,
                        help_text="URL for hero section background image",
                        null=True,
                    ),
                ),
                (
                    "hero_cta_button_text",
                    models.CharField(
                        default="Explore Projects",
                        help_text="Call-to-action button text",
                        max_length=50,
                    ),
                ),
                (
                    "stats_experience_value",
                    models.CharField(
                        default="15+",
                        help_text="Years of experience (e.g., 15+)",
                        max_length=20,
                    ),
                ),
                (
                    "stats_experience_label",
                    models.CharField(
                        default="Years of Excellence",
                        help_text="Label for experience stat",
                        max_length=100,
                    ),
                ),
                (
                    "stats_projects_value",
                    models.CharField(
                        default="50+",
                        help_text="Number of projects completed (e.g., 50+)",
                        max_length=20,
                    ),
                ),
                (
                    "stats_projects_label",
                    models.CharField(
                        default="Projects Completed",
                        help_text="Label for projects stat",
                        max_length=100,
                    ),
                ),
                (
                    "stats_families_value",
                    models.CharField(
                        default="2000+",
                        help_text="Number of happy families (e.g., 2000+)",
                        max_length=20,
                    ),
                ),
                (
                    "stats_families_label",
                    models.CharField(
                        default="Happy Families",
                        help_text="Label for families stat",
                        max_length=100,
                    ),
                ),
                (
                    "stats_sqft_value",
                    models.CharField(
                        default="10L+",
                        help_text="Square feet delivered (e.g., 10L+)",
                        max_length=20,
                    ),
                ),
                (
                    "stats_sqft_label",
                    models.CharField(
                        default="Sq.Ft Delivered",
                        help_text="Label for sqft stat",
                        max_length=100,
                    ),
                ),
                (
                    "footer_office_address",
                    models.TextField(
                        default="HSR Green Homes, Karimnagar, Telangana 505001",
                        help_text="Complete office address for footer",
                    ),
                ),
                (
                    "footer_phone_number",
                    models.CharField(
                        default="+91 9876543210",
                        help_text="Primary contact phone number",
                        max_length=20,
                    ),
                ),
                (
                    "footer_email",
                    models.EmailField(
                        default="info@hsrgreenhomes.com",
                        help_text="Primary contact email",
                        max_length=254,
                    ),
                ),
                (
                    "footer_whatsapp_number",
                    models.CharField(
                        default="+91 9876543210",
                        help_text="WhatsApp contact number",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Home Page Content",
                "verbose_name_plural": "Home Page Content",
                "db_table": "home_page_content",
            },
        ),
        migrations.CreateModel(
            name="FeaturedProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "display_order",
                    models.IntegerField(
                        default=0,
                        help_text="Order in which to display (lower number = higher priority)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this featured project is currently active",
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        help_text="Project to feature on homepage",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="featured_placement",
                        to="api.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Featured Project",
                "verbose_name_plural": "Featured Projects",
                "db_table": "featured_projects",
                "ordering": ["display_order", "-created_at"],
                "unique_together": {("project",)},
            },
        ),
    ]
