# Generated by Django 5.0.7 on 2025-11-16 18:12

import api.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_homepagecontent_featuredproject"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectFloorPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "title",
                    models.CharField(help_text="e.g., 2BHK Floor Plan", max_length=255),
                ),
                (
                    "file_url",
                    models.URLField(
                        blank=True,
                        help_text="External URL for floor plan file",
                        null=True,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Upload floor plan file (PDF or Image)",
                        null=True,
                        upload_to=api.models.project_floor_plan_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                ("display_order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Floor Plan",
                "verbose_name_plural": "Floor Plans",
                "db_table": "project_floor_plans",
                "ordering": ["display_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectGalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="External URL for gallery image",
                        null=True,
                    ),
                ),
                (
                    "image_file",
                    models.ImageField(
                        blank=True,
                        help_text="Upload gallery image file",
                        null=True,
                        upload_to=api.models.project_gallery_image_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "webp"]
                            )
                        ],
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("display_order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Gallery Image",
                "verbose_name_plural": "Gallery Images",
                "db_table": "project_gallery_images",
                "ordering": ["display_order", "created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="project",
            name="hero_image",
        ),
        migrations.AddField(
            model_name="project",
            name="amenities",
            field=models.JSONField(
                default=dict,
                help_text="Project amenities: {swimming_pool: true, gym: false, ...}",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="brochure_file",
            field=models.FileField(
                blank=True,
                help_text="Upload brochure PDF file",
                null=True,
                upload_to=api.models.project_brochure_path,
                validators=[django.core.validators.FileExtensionValidator(["pdf"])],
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="brochure_url",
            field=models.URLField(
                blank=True,
                help_text="External URL for brochure PDF (if not uploading file)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="configurations",
            field=models.JSONField(
                default=dict,
                help_text="Project configurations: {1BHK: true, 2BHK: false, ...}",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin user who created this project",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="hero_image_file",
            field=models.ImageField(
                blank=True,
                help_text="Upload hero image file",
                null=True,
                upload_to=api.models.project_hero_image_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="hero_image_url",
            field=models.URLField(
                blank=True,
                help_text="External URL for hero image (if not uploading file)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, max_length=300, unique=True),
        ),
        migrations.AddField(
            model_name="project",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin user who last updated this project",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="view_count",
            field=models.IntegerField(
                default=0, help_text="Number of times project was viewed"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(help_text="Detailed project description"),
        ),
        migrations.AlterField(
            model_name="project",
            name="is_featured",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Featured projects appear on homepage",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="location",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="project",
            name="rera_number",
            field=models.CharField(
                db_index=True,
                help_text="Unique RERA registration number",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("upcoming", "Upcoming"),
                    ("ongoing", "Ongoing"),
                    ("completed", "Completed"),
                ],
                db_index=True,
                default="upcoming",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["status", "is_deleted"], name="projects_status_37c291_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["is_featured", "is_deleted"], name="projects_is_feat_4e0d3a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["created_at"], name="projects_created_40bcd1_idx"
            ),
        ),
        migrations.AddField(
            model_name="projectfloorplan",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="floor_plans",
                to="api.project",
            ),
        ),
        migrations.AddField(
            model_name="projectgalleryimage",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gallery_images",
                to="api.project",
            ),
        ),
    ]
