# Generated by Django 5.0.7 on 2025-11-16 21:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_projectfloorplan_projectgalleryimage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="follow_up_count",
            field=models.IntegerField(
                default=0, help_text="Number of times this lead has been followed up"
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="next_follow_up",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Scheduled date/time for next follow-up",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="preferred_contact_method",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("phone", "Phone"),
                    ("whatsapp", "WhatsApp"),
                ],
                default="phone",
                help_text="Customer preferred contact method",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("urgent", "Urgent"),
                ],
                db_index=True,
                default="medium",
                help_text="Lead priority level",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (1, "1 Star"),
                    (2, "2 Stars"),
                    (3, "3 Stars"),
                    (4, "4 Stars"),
                    (5, "5 Stars"),
                ],
                db_index=True,
                default=5,
                help_text="Customer rating (1-5 stars)",
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="verified",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether this testimonial has been verified by admin",
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="email",
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="lead",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="lead",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Internal notes about this lead"
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="phone",
            field=models.CharField(
                db_index=True,
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Invalid phone number format", regex="^\\+?1?\\d{9,15}$"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="source",
            field=models.CharField(
                choices=[
                    ("contact_form", "Contact Form"),
                    ("whatsapp", "WhatsApp"),
                    ("phone_call", "Phone Call"),
                    ("walk_in", "Walk In"),
                ],
                db_index=True,
                default="contact_form",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("contacted", "Contacted"),
                    ("qualified", "Qualified"),
                    ("closed", "Closed"),
                ],
                db_index=True,
                default="new",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="customer_name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="display_order",
            field=models.IntegerField(
                default=0,
                help_text="Order in which to display (lower number = higher priority)",
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Whether to show this testimonial on website",
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["status", "priority"], name="leads_status_deebb6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["next_follow_up"], name="leads_next_fo_9ca5a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["priority", "status"], name="leads_priorit_85ace6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testimonial",
            index=models.Index(
                fields=["is_active", "rating"], name="testimonial_is_acti_d37676_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testimonial",
            index=models.Index(
                fields=["verified", "is_active"], name="testimonial_verifie_a21a29_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testimonial",
            index=models.Index(
                fields=["project", "is_active"], name="testimonial_project_2749a7_idx"
            ),
        ),
    ]
