# Generated by Django 5.0.7 on 2025-11-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_projectfloorplan_projectgalleryimage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "whatsapp_enabled",
                    models.BooleanField(
                        default=True, help_text="Enable WhatsApp integration"
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        default="+91 9876543210",
                        help_text="WhatsApp contact number",
                        max_length=20,
                    ),
                ),
                (
                    "whatsapp_business_hours",
                    models.CharField(
                        default="9:00 AM - 8:00 PM",
                        help_text="WhatsApp business hours",
                        max_length=100,
                    ),
                ),
                (
                    "whatsapp_auto_reply",
                    models.TextField(
                        default="Hello! Thank you for contacting HSR Green Homes. We will get back to you shortly.",
                        help_text="WhatsApp auto-reply message",
                    ),
                ),
                (
                    "primary_phone",
                    models.CharField(
                        default="+91 9876543210",
                        help_text="Primary phone number",
                        max_length=20,
                    ),
                ),
                (
                    "secondary_phone",
                    models.CharField(
                        blank=True,
                        help_text="Secondary phone number",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "toll_free_number",
                    models.CharField(
                        blank=True,
                        help_text="Toll-free number",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "phone_business_hours",
                    models.CharField(
                        default="9:00 AM - 6:00 PM",
                        help_text="Phone business hours",
                        max_length=100,
                    ),
                ),
                (
                    "info_email",
                    models.EmailField(
                        default="info@hsrgreenhomes.com",
                        help_text="Info email address",
                        max_length=254,
                    ),
                ),
                (
                    "sales_email",
                    models.EmailField(
                        default="sales@hsrgreenhomes.com",
                        help_text="Sales email address",
                        max_length=254,
                    ),
                ),
                (
                    "support_email",
                    models.EmailField(
                        default="support@hsrgreenhomes.com",
                        help_text="Support email address",
                        max_length=254,
                    ),
                ),
                (
                    "email_auto_reply_enabled",
                    models.BooleanField(
                        default=True, help_text="Enable email auto-reply"
                    ),
                ),
                (
                    "email_auto_reply_subject",
                    models.CharField(
                        default="Thank you for contacting HSR Green Homes",
                        help_text="Email auto-reply subject",
                        max_length=255,
                    ),
                ),
                (
                    "email_auto_reply_message",
                    models.TextField(
                        default="We have received your inquiry and will respond within 24 hours.",
                        help_text="Email auto-reply message",
                    ),
                ),
                (
                    "street_address",
                    models.CharField(
                        default="HSR Green Homes Building",
                        help_text="Street address",
                        max_length=255,
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        default="Karimnagar", help_text="Area/Locality", max_length=100
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        default="Karimnagar", help_text="City", max_length=100
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        default="Telangana", help_text="State", max_length=100
                    ),
                ),
                (
                    "pincode",
                    models.CharField(
                        default="505001", help_text="Pincode", max_length=10
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="India", help_text="Country", max_length=100
                    ),
                ),
                (
                    "google_maps_embed_code",
                    models.TextField(
                        blank=True, help_text="Google Maps embed code or URL", null=True
                    ),
                ),
                (
                    "facebook_url",
                    models.URLField(
                        blank=True, help_text="Facebook page URL", null=True
                    ),
                ),
                (
                    "instagram_url",
                    models.URLField(
                        blank=True, help_text="Instagram profile URL", null=True
                    ),
                ),
                (
                    "twitter_url",
                    models.URLField(
                        blank=True, help_text="Twitter profile URL", null=True
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(
                        blank=True, help_text="LinkedIn company URL", null=True
                    ),
                ),
                (
                    "youtube_url",
                    models.URLField(
                        blank=True, help_text="YouTube channel URL", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Settings",
                "verbose_name_plural": "Contact Settings",
                "db_table": "contact_settings",
            },
        ),
        migrations.AddField(
            model_name="systemstatus",
            name="auto_backup",
            field=models.BooleanField(
                default=False, help_text="Enable automatic daily backups"
            ),
        ),
        migrations.AddField(
            model_name="systemstatus",
            name="email_notifications",
            field=models.BooleanField(
                default=True, help_text="Enable email notifications for new leads"
            ),
        ),
        migrations.AddField(
            model_name="systemstatus",
            name="site_name",
            field=models.CharField(
                default="HSR Green Homes", help_text="Site name", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="systemstatus",
            name="site_url",
            field=models.URLField(
                default="https://hsrgreenhomes.com", help_text="Site URL"
            ),
        ),
        migrations.AlterField(
            model_name="systemstatus",
            name="session_timeout",
            field=models.IntegerField(
                default=30, help_text="Session timeout in minutes"
            ),
        ),
    ]
