# Generated by Django 5.0.7 on 2025-11-16 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_lead_follow_up_count_lead_next_follow_up_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "whatsapp_enabled",
                    models.BooleanField(
                        default=True, help_text="Enable WhatsApp integration"
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        default="+919876543210",
                        help_text="WhatsApp business number",
                        max_length=20,
                    ),
                ),
                (
                    "whatsapp_business_hours",
                    models.CharField(
                        default="9:00 AM - 8:00 PM",
                        help_text="WhatsApp availability hours",
                        max_length=100,
                    ),
                ),
                (
                    "whatsapp_auto_reply",
                    models.TextField(
                        default="Hello! Thank you for contacting HSR Green Homes. We will get back to you shortly.",
                        help_text="Auto-reply message for WhatsApp",
                    ),
                ),
                (
                    "primary_phone",
                    models.CharField(
                        default="+919876543210",
                        help_text="Primary contact phone number",
                        max_length=20,
                    ),
                ),
                (
                    "secondary_phone",
                    models.CharField(
                        blank=True,
                        default="+919876543211",
                        help_text="Secondary contact phone number",
                        max_length=20,
                    ),
                ),
                (
                    "toll_free_number",
                    models.CharField(
                        blank=True,
                        default="1800-123-4567",
                        help_text="Toll-free number",
                        max_length=20,
                    ),
                ),
                (
                    "phone_business_hours",
                    models.CharField(
                        default="9:00 AM - 6:00 PM",
                        help_text="Phone availability hours",
                        max_length=100,
                    ),
                ),
                (
                    "info_email",
                    models.EmailField(
                        default="info@hsrgreenhomes.com",
                        help_text="General information email",
                        max_length=254,
                    ),
                ),
                (
                    "sales_email",
                    models.EmailField(
                        default="sales@hsrgreenhomes.com",
                        help_text="Sales inquiries email",
                        max_length=254,
                    ),
                ),
                (
                    "support_email",
                    models.EmailField(
                        default="support@hsrgreenhomes.com",
                        help_text="Customer support email",
                        max_length=254,
                    ),
                ),
                (
                    "email_auto_reply_enabled",
                    models.BooleanField(
                        default=True, help_text="Enable email auto-reply"
                    ),
                ),
                (
                    "email_auto_reply_subject",
                    models.CharField(
                        default="Thank you for contacting HSR Green Homes",
                        help_text="Auto-reply email subject",
                        max_length=255,
                    ),
                ),
                (
                    "email_auto_reply_message",
                    models.TextField(
                        default="We have received your inquiry and will respond within 24 hours.",
                        help_text="Auto-reply email message",
                    ),
                ),
                (
                    "street_address",
                    models.CharField(
                        default="HSR Green Homes Building",
                        help_text="Street address",
                        max_length=255,
                    ),
                ),
                (
                    "area_locality",
                    models.CharField(
                        default="Karimnagar",
                        help_text="Area or locality",
                        max_length=255,
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        default="Karimnagar", help_text="City", max_length=100
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        default="Telangana", help_text="State", max_length=100
                    ),
                ),
                (
                    "pincode",
                    models.CharField(
                        default="505001", help_text="Pincode/ZIP code", max_length=10
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="India", help_text="Country", max_length=100
                    ),
                ),
                (
                    "google_maps_embed",
                    models.TextField(
                        blank=True, help_text="Google Maps iframe embed code"
                    ),
                ),
                (
                    "facebook_url",
                    models.URLField(
                        blank=True,
                        default="https://facebook.com/hsrgreenhomes",
                        help_text="Facebook page URL",
                    ),
                ),
                (
                    "instagram_url",
                    models.URLField(
                        blank=True,
                        default="https://instagram.com/hsrgreenhomes",
                        help_text="Instagram profile URL",
                    ),
                ),
                (
                    "twitter_url",
                    models.URLField(
                        blank=True,
                        default="https://twitter.com/hsrgreenhomes",
                        help_text="Twitter profile URL",
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(
                        blank=True,
                        default="https://linkedin.com/company/hsrgreenhomes",
                        help_text="LinkedIn company URL",
                    ),
                ),
                (
                    "youtube_url",
                    models.URLField(
                        blank=True,
                        default="https://youtube.com/hsrgreenhomes",
                        help_text="YouTube channel URL",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Settings",
                "verbose_name_plural": "Contact Settings",
                "db_table": "contact_settings",
            },
        ),
        migrations.AddField(
            model_name="systemstatus",
            name="auto_backup_enabled",
            field=models.BooleanField(
                default=True, help_text="Enable automatic daily backups"
            ),
        ),
        migrations.AddField(
            model_name="systemstatus",
            name="email_notifications_enabled",
            field=models.BooleanField(
                default=True, help_text="Receive email notifications for new leads"
            ),
        ),
        migrations.AddField(
            model_name="systemstatus",
            name="maintenance_message",
            field=models.TextField(
                default="We are currently performing maintenance. Please check back soon.",
                help_text="Message to display during maintenance",
            ),
        ),
        migrations.AddField(
            model_name="systemstatus",
            name="meta_description",
            field=models.TextField(
                blank=True, help_text="Default meta description for SEO"
            ),
        ),
        migrations.AddField(
            model_name="systemstatus",
            name="meta_keywords",
            field=models.CharField(
                blank=True, help_text="Default meta keywords for SEO", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="systemstatus",
            name="meta_title",
            field=models.CharField(
                blank=True, help_text="Default meta title for SEO", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="systemstatus",
            name="notification_email",
            field=models.EmailField(
                default="admin@hsrgreenhomes.com",
                help_text="Email address to receive notifications",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="systemstatus",
            name="site_name",
            field=models.CharField(
                default="HSR Green Homes",
                help_text="Website/company name",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="systemstatus",
            name="site_url",
            field=models.URLField(
                default="https://hsrgreenhomes.com", help_text="Primary website URL"
            ),
        ),
        migrations.AlterField(
            model_name="systemstatus",
            name="contact_forms_working",
            field=models.BooleanField(
                default=True, help_text="Contact forms working status"
            ),
        ),
        migrations.AlterField(
            model_name="systemstatus",
            name="last_backup_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Last backup timestamp"
            ),
        ),
        migrations.AlterField(
            model_name="systemstatus",
            name="maintenance_mode",
            field=models.BooleanField(
                default=False,
                help_text="Enable maintenance mode (disables public access)",
            ),
        ),
        migrations.AlterField(
            model_name="systemstatus",
            name="website_status",
            field=models.BooleanField(
                default=True, help_text="Website online/offline status"
            ),
        ),
        migrations.AlterField(
            model_name="systemstatus",
            name="whatsapp_integration_active",
            field=models.BooleanField(
                default=True, help_text="WhatsApp integration active status"
            ),
        ),
    ]
