# Generated by Django 5.0.7 on 2026-02-04 18:40

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_about_our_story_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to=api.models.award_image_path)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Award',
                'verbose_name_plural': 'Awards',
                'db_table': 'about_awards',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='google_map_embed_url',
            field=models.TextField(blank=True, help_text='Google Map Embed Code or URL', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed project description', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='rera_number',
            field=models.CharField(blank=True, db_index=True, help_text='Unique RERA registration number', max_length=100, null=True, unique=True),
        ),
    ]
