# Generated by Django 5.0.7 on 2026-02-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_award_project_google_map_embed_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Order for custom sorting'),
        ),
    ]
